name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: windows-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for visiting my git'
        pr-message: 'Github is a goog environment for developers'
